import java.security.cert.X509Certificate;

import de.prob.model.representation.*

s = api.b_load(dir+File.separator+"machines"+File.separator+"scheduler.mch")
x = ModelRep.translate(s)
assert x.size() == 1
scheduler = x[0]
assert scheduler.label == "scheduler"
assert scheduler.children.size() == 4

"Tests the model representation generated by ModelRep"