package de.prob.visualization

class HTMLResources {

	def static String getPredicateHTML(String sessionId, String w, String h) {
		if(w != null && h != null) {
			String loadcmd = "createFormulaViz('${sessionId}', 'body', ${w}, ${h})"
			return getHTML(loadcmd,"Predicate Visualization","predicate.css","predicate.js")
		}
		String loadcmd = "initialize('${sessionId}')"
		return getHTML(loadcmd,"Predicate Visualization","predicate.css","predicate.js")
	}

	def static String getValueVsTimeHTML(String sessionId, String w, String h) {
		if(w != null && h != null) {
			String loadcmd = "createValueOverTimeViz('${sessionId}', 'body', ${w}, ${h}, 600, 400)"
			return getHTML(loadcmd,"Value vs Time","valueOverTime.css","oszilloscope.js")
		}
		String loadcmd = "initialize('${sessionId}')"
		return getHTML(loadcmd,"Value vs Time","valueOverTime.css","oszilloscope.js")
	}

	public static String getSSVizHTML(String sessionId, String w, String h) {
		if(w != null && h != null) {
			String loadcmd = "createSSGraph('${sessionId}','body',1,[],${w},${h})"
			return getHTML(loadcmd,"State Space Visualization","statespace.css","statespace.js")
		}

		String loadcmd = "initialize('${sessionId}')"
		return getHTML(loadcmd,"State Space Visualization","statespace.css","statespace.js");
	}

	/**
	 * @param sessionId (Generated by the servlet)
	 * @param stylesheet ( "MyStyleSheet.css" that is saved in folder stylesheets/visualizations )
	 * @param javascript ( "MyJavascript.js" that is saved in folder javascripts )
	 * @return String representation of the HTML for the page
	 */
	def static String getHTML(String loadcmd, String title, String stylesheet, String javascript) {
		return '''<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<!-- Basic Page Needs
    ================================================== -->
<meta charset="utf-8">
<title>'''+title+'''</title>
<meta name="description" content="">
<meta name="author" content="Joy Clark">

<!-- Mobile Specific Metas
    ================================================== -->
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
    ================================================== -->
<link rel="stylesheet" href="../stylesheets/skeleton.css">
<link rel="stylesheet" href="../stylesheets/layout.css">
<link rel="stylesheet" href="../stylesheets/evalb.css">
<link rel="stylesheet" href="../stylesheets/pepper.css">
<link rel="stylesheet" href="../stylesheets/visualizations/'''+stylesheet+'''"
</head>
<body onload="'''+loadcmd+'''">

			<div id="body"></div>

			<!-- JS
			  ================================================== -->
			<!-- <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script> -->
			<script src="../javascripts/jquery-1.9.1.min.js"></script>
			<script src="../javascripts/d3.v2.min.js"></script>
			<script src="../javascripts/viz.js"></script>
			<script src="../javascripts/prob_visualization.js"></script>
			<script src="../javascripts/'''+javascript+'''"></script>

			<!-- End Document
		  ================================================== -->
		</body>
		</html>'''
	}
}
